### ISSUE TITLE
Jeckyll not Building

### ISSUE THREAD

**Issue by syswsi** [NeuroTechX/learn.neurotechedu.com#16]
When I push any commitment to Github Pages, I get a general message stating that the github page cannot be built.

**Comment by francescacoo** [comment]
Hey syswsi,
I tried to build it locally and I had a problem with the contributors.md.
It was giving an error because of the step 3 where {% include is mentioned
I put a space between the { and % and it worked, built and could see it in localhost.

That might not be the problem, first time that I try jekyll, but I thought to mention it :)

**Comment by syswsi** [comment]
Tried that but didn't work :(.

Can you post the error message you got?

**Comment by syswsi** [comment]
Omg.

I think it's working.

It looks like it was a Div issue.

Wooooooooooooooooo

**Comment by syswsi** [comment]
nvm....

**Comment by syswsi** [comment]
wait........ I think it solved. After your comment, I reviewed the other {%
blocks and I think the issue was with the comments section.

Woooooo! I think it's solved???

**Comment by syswsi** [comment]
So yea, looks like that was the issue. We got to just clean up the formatting, but that shouldn't take up much time :):):):):)
