### ISSUE TITLE
Fix Contributors section.

### ISSUE THREAD

**Issue by syswsi** [NeuroTechX/learn.neurotechedu.com#23]

**Comment by jnaulty** [comment]
Hey @syswsi 
Making an attempt on [PR24](https://github.com/NeuroTechX/learn.neurotechedu.com/pull/24)
I fixed some formatting, and added some html `row`s to make 2 columns.

It's possible to template this, so that contributors can be generated from a yaml configuration file.
An example of this can be demonstrated in this commit: [Here](https://github.com/jnaulty/learn.neurotechedu.com/commit/b1a999d8e39321bc604ef0bdc645a4d842da7389) is an example of what a yaml config might look like. If you were interested in going in that direction.

**Comment by jnaulty** [comment]
I think a slightly more elegant solution would look like this: https://github.com/NeuroTechX/learn.neurotechedu.com/pull/25
What do you think? @syswsi

**Comment by syswsi** [comment]
I love it! I'll merge it.
